apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.secrets.name }}"
  namespace: "{{ .Release.Namespace }}"
type: Opaque
stringData:
  api_key: "{{ .Values.secrets.api_key }}"
  protocol: "{{ .Values.secrets.protocol }}"
  host: "{{ .Values.secrets.host }}"
  sentry_dsn: "{{ .Values.secrets.sentry_dsn }}"
  sentry_environment: "{{ .Values.secrets.sentry_environment }}"
